### PR TITLE
refactor: switch to es2022 build

### PR DESCRIPTION
**Pull request by hwbllmnn**
## Description

Switches to an es2022 build. Downstream projects may need to adjust their config to properly transform the library files for the browser (depending on the used bundler).

## Pull request type

- [ ] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## Do you introduce a breaking change?

- [x] Yes
- [ ] No

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the
  [BSD-2-Clause](https://github.com/terrestris/react-geo/blob/main/LICENSE).
- [x] I have followed the [guidelines for contributing](https://github.com/terrestris/react-geo/blob/main/CONTRIBUTING.md).
- [x] The proposed change fits to the content of the [Code of Conduct](https://github.com/terrestris/react-geo/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally).
- [ ] I have added a screenshot/screencast to illustrate the visual output of my update.

@terrestris/devs Please review.

### CODE REVIEW

**Comment by KaiVolland** [comment]
Is this a breaking change? If yes please squash with an appropriate commit message. e.g.: `refactor!: switch to es2022 build`

**Comment by hwbllmnn** [comment]
> Is this a breaking change? If yes please squash with an appropriate commit message. e.g.: `refactor!: switch to es2022 build`

Done

**Review by KaiVolland — APPROVED** [review]

**Pull request merged**
