### PR TITLE
Change references to OL documentation in comments to the latest format

### PR DESCRIPTION
**Pull request by PeterC66**
### Description:
The comments in 3 modules refer to OpenLayers documentation in /latest/apidoc/. OL has changed the format of the URL, and this PR updates the comments to the current format.

Note that in three cases in DigitizeButton.jsx the events mentioned in the comments are (no longer?) referred to on the OL documentation page. This might indicate the comment itself needs updating, as well as the URL - but I do not know enough to decide.

The relevant interactions and events are:

- Modify.Event : modifystart and modifyend events
- Translate.Event: translatestart, translateend and translating events
- Select.Event: select event

### CODE REVIEW

**Comment by marcjansen** [comment]
Thanks for this. Are you able and willing to fix the merge conflicts? If not tell us so, and we'll either give advice or fix them on our side.

**Comment by PeterC66** [comment]
I think I have resolved the conflict - it was just one line in one file @type {object}-> @type {Object}.

**Comment by marcjansen** [comment]
> I think I have resolved the conflict 

Nice. Yes the conflicts are resolved.

**Comment by marcjansen** [comment]
Changes look good to me. The comment wrt the missing events has to be fixed on the OpenLayers side, the documentation there isn't at 100% right now.

I'll merge this once Travis is green. Thanks @PeterC66.

**Pull request merged**
