### PR TITLE
Introduce styleguidist

### PR DESCRIPTION
**Pull request by dnlkoch**
### Description:

This introduces [styleguidist](https://github.com/styleguidist/react-styleguidist).

See related issues #488, #396, #207, #64.

### CODE REVIEW

**Comment by KaiVolland** [comment]
Really love this. Nice to see how many packages are removed from package.json and the result of docs and exmaples looks much better.




I just reviewed the critical files, which seem to look good.

**Comment by marcjansen** [comment]
Regarding the recent build failures: are the following peer dependencies installed?

```
npm WARN html-webpack-plugin@2.30.1 requires a peer of extract-text-webpack-plugin@^1.0.0 || ^2.0.0 || 3.0.0 || ^4.0.0-alpha.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN uglifyjs-webpack-plugin@1.1.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@2.11.2 requires a peer of webpack@^2.2.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@1.12.2 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
```

A wild guess.

**Comment by marcjansen** [comment]
dont we also need webpack-cli

**Comment by dnlkoch** [comment]
Thanks everyone!

**Comment by marcjansen** [comment]
Is this online somwhere? under components on the website I get a white page...

**Comment by dnlkoch** [comment]
Please check again [here](https://terrestris.github.io/react-geo/docs/latest/index.html), I had to fix some ignores in the `gh-pages` branch.

**Comment by marcjansen** [comment]
Thanks. Very nice.

**Pull request merged**
