### PR TITLE
Remove usage of deprecated lifecycle methods

### PR DESCRIPTION
**Pull request by dnlkoch**
### Description:

This fixes the usage of all deprecated ReactJS lifecycle methods (see #648) and updates the `eslint-plugin-react` to the current release (closes #647).

### CODE REVIEW

**Comment by marcjansen** [comment]
Very nice! I had started sth. but failed some days ago in the train... thanks for this. In my case some timing was different than expected in the tests and possibly also in the examples. Did you notice anything there?

Please let another developer look over it before merging.

**Comment by dnlkoch** [comment]
No, actually I had no timing issues while porting. Do you remember the component the test/s failed for?

**Comment by marcjansen** [comment]
double checking right now

**Comment by marcjansen** [comment]
[Here are my changes from back then, unfinished](https://github.com/terrestris/react-geo/compare/master...marcjansen:update-dependencies) It looks mostly like your PR.

But I just saw that the failing tests are due to eslint erroring / it was simply not done.

So probably nothing to worry about.

**Comment by dnlkoch** [comment]
Thanks for the reviews!

**Pull request merged**
