### PR TITLE
Return Promises in async CircleMenu / CircleMenuItem tests

### PR DESCRIPTION
**Pull request by dnlkoch**
### Description:

This tries to fix the randomly failing tests in the Node 10 environment by returning Promises in the asynchronous `CircleMenu` / `CircleMenuItem` tests.

### CODE REVIEW

**Comment by dnlkoch** [comment]
Yeah, I just noticed your fix in #631 :smile: 

It should be almost the same, but it refactors the spec for the `CircleMenuItem` as well. Calls to `done()` should be removed likewise or did I miss anything?

**Comment by marcjansen** [comment]
> Calls to done() should be removed likewise or did I miss anything?

I don't know, TBH. You decide.

**Comment by marcjansen** [comment]
I'll rebase #631 after merging…

**Comment by dnlkoch** [comment]
Alright, let's get this one merged…

**Comment by marcjansen** [comment]
For what it's worth: this also fixed the build on #631: [Travis-Log](https://travis-ci.org/terrestris/react-geo/builds/383115146?utm_source=github_status&utm_medium=notification)

**Pull request merged**
