### PR TITLE
Init husky commit lint

### PR DESCRIPTION
**Pull request by dnlkoch**
## Description

This initializes [husky](https://github.com/typicode/husky) in combination with [commitlint](https://commitlint.js.org/#/) to enforce [semantic commit messages](https://sparkbox.com/foundry/semantic_commit_messages). Prior this was checked with the [`Semantic Pull Requests`](https://github.com/zeke/semantic-pull-requests) app which is currently no longer maintained.

Please review @terrestris/devs.

## Related issues or pull requests

See #2624.

## Pull request type

- [ ] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the
  [BSD-2-Clause](https://github.com/terrestris/react-geo/blob/main/LICENSE).
- [x] I have followed the [guidelines for contributing](https://github.com/terrestris/react-geo/blob/main/CONTRIBUTING.md).
- [x] The proposed change fits to the content of the [Code of Conduct](https://github.com/terrestris/react-geo/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally).
- [ ] I have added a screenshot/screencast to illustrate the visual output of my update.

### CODE REVIEW

**Review by hwbllmnn — APPROVED** [review]

**Comment by dnlkoch** [comment]
Thanks for the review!

**Review by KaiVolland — APPROVED** [review]
Nice. Feel free to merge.

There was no config for the semantic pull request app that has to be removed i guess?

**Review by marcjansen — APPROVED** [review]
Loks good to me.

**Pull request merged**
