### PR TITLE
Upgrade to OpenLayers v5

### LINKED ISSUE #515: Upgrade to ol v5
As @ahocevar suggested in his FOSSGIS talk.

We should prepare the upgrade of ol. If i'm right the main change will be the import pathes. As the classes are now written in UpperCase.

Maybe this will be an API-breaking change…

### PR DESCRIPTION
**Pull request by marcjansen**
### Description:

This supersedes #606 (this is a rebased version for which the build passes.)

Let's stay tuned and be compatible with prospective avaliable upgraded OpenLayers v5.x! :man_cartwheeling: 

This PR contains first steps to get married with newest `ol` which is currently avaliable as [v5.0.0-beta.10](https://github.com/openlayers/openlayers/tree/beta).

Most important changes:
* all `ol` classes imports are in camelcase now
* for the following classes the named imports for affected functions are used now:
  * `ol/easing`
  * `ol/proj`
  * `ol/proj/proj4`
  * `ol/extent`
  * `ol/interaction/Draw`
  * `ol/events/Condition`
  * `ol/Observable`
  * `ol/sphere`
  * `ol/format/Filter`

Upgrade considers notes mentioned [here](https://github.com/openlayers/openlayers/wiki/OpenLayers-v5.x) and [here](https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md).
 
Enjoy! :pineapple: 

Fixes #515

### CODE REVIEW

**Comment by dnlkoch** [comment]
I recognized the failing [test](https://github.com/terrestris/react-geo/blob/master/src/CircleMenu/CircleMenuItem/CircleMenuItem.spec.jsx#L27) in another PR as well and I think it's not related to the changes made here. Dealing with `setTimeout()` with a fixed timeout is always tricky…

**Comment by dnlkoch** [comment]
Apparently #667 fixes the failing tests. It's almost the same change as introduced here (thanks @marcjansen), but it also overhauls the tests in the `CircleMenuItem` spec.

**Comment by marcjansen** [comment]
> I'll try to tackle still existing conflicts tonight 

That is nice, thanks.

> and prepare this PR for merging.

Before merging we should release. The first release which contains this PR shold IMO be a major release with clear advice what is needed in projects to make  use of that new release.

Thanks.

**Comment by annarieger** [comment]
I totally agree with all your points @marcjansen. That's why I wrote "prepare for merging".. This doesn't mean that I'm gonna do it directly 😉

**Comment by annarieger** [comment]
PR is ready for review now. It's rebased to include all significant changes from `master` branch and supports currently latest avaliable release `v5.0.2` of `ol`.

As @marcjansen mentioned above, we should **mandatory** release `react-geo` due to breaking changes in the API before this one is merged.

**Comment by KaiVolland** [comment]
Is there a general update strategy?  New features only to for OL5?

**Comment by marcjansen** [comment]
> Is there a general update strategy? New features only to for OL5?

@KaiVolland See description: 

> Upgrade considers notes mentioned [here](https://github.com/openlayers/openlayers/wiki/OpenLayers-v5.x) and [here](https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md).

Let's just release a new minor with the latest changes and then release a new ajor with this in. The major is justifuied due to changed peer dependency. release notes should include a big marker linking to the above documents.

**Comment by KaiVolland** [comment]
Sry my question wasn't precise enough.
I wanted to know how `react-geo` should handle new features of `react-geo`. So will we continue to support v8 (ol4) or will we just add new features to >v9 (ol5). Bugs should be fixed for both i think.

**Comment by marcjansen** [comment]
OK, I get your question now. I am unsure to be honest. I think it is enoigh to first only further develop on v9 (ol@5), and only in rare circumstances releas old bugfixes for v8. This will put pressure on applications running on v8 I know, but generally this is a good thing. And we can always release a point release with just the needed fixes, right?

**Pull request merged**
