### PR TITLE
Fixes DigitizeButton bugs

### PR DESCRIPTION
**Pull request by KaiVolland**
### Description:

This fixes buggy behaviour of the `DigitizeButton`.
- Most important fix is to not set a style on the feature but use the existing style functions.
- The label is know set as an feature attribute not at the style.

### CODE REVIEW

**Comment by dnlkoch** [comment]
I understand the changes, but could you please explain the buggy behaviour? I think setting the style for each features was intended to allow different styles inside the layer.

Otherwise, LGTM!

**Comment by KaiVolland** [comment]
@dnlkoch 
The `setStyle` on the features where called inside of a styleFunction. :thinking: 
IMHO the styleFunction is the right place to create different styles inside a layer but you should never call `setStyle` but return the appropriate style.

**Comment by dnlkoch** [comment]
Ok, thanks for the clarification!

**Comment by KaiVolland** [comment]
Changing the style per feature should definetly be (re-)implemented later. Maybe we can tackle this together with #475

**Pull request merged**
