### PR TITLE
Set style on drawn features

### PR DESCRIPTION
**Pull request by annarieger**
### Description:
* Set `ol.style.Style` object on drawn feature (previously the style was set on source of `digitizeLayer`)
* Added `styleFunction` for selected feature which will be applied if `ol.interaction.Select` in `editType=Edit` mode is activated.

Please review @terrestris/devs

### CODE REVIEW

**Comment by annarieger** [comment]
Thanks for review! :pineapple: 
Merging now..

**Comment by KaiVolland** [comment]
@annarieger Do we have to do a feature or a bugfix release?

**Comment by annarieger** [comment]
I think that's more a feature as a bugfix.

**Comment by KaiVolland** [comment]
Ok so could you make a release? Or should I?

**Comment by annarieger** [comment]
Fell free to release please

**Pull request merged**
