### PR TITLE
refactor(print): remove the print layout from code, use template func…

### PR DESCRIPTION
**Pull request by weskamm**
## Breaking Change

This moves hardcoded print layouting from the code to templates.
Four example templates have been created (A3 / A4 Portrait and Landscape) to show the usage.
A utility class has been added for better code reusage.

image
image

### Migration advice
When printing a PDF you now have to provide a specific print layout / template, as the hardcoded one has been removed.
See the updated example of the PrintButton to see how it works.

@terrestris/devs please review

## Pull request type

- [ ] Bugfix
- [x] Feature
- [ ] Dependency updates
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## Do you introduce a breaking change?

- [x] Yes
- [ ] No

## Checklist

- [ ] I understand and agree that the changes in this PR will be licensed under the
  [BSD-2-Clause](https://github.com/terrestris/react-geo/blob/main/LICENSE).
- [ ] I have followed the [guidelines for contributing](https://github.com/terrestris/react-geo/blob/main/CONTRIBUTING.md).
- [ ] The proposed change fits to the content of the [Code of Conduct](https://github.com/terrestris/react-geo/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally).
- [ ] I have added a screenshot/screencast to illustrate the visual output of my update.

### CODE REVIEW

**Comment by hblitza** [comment]
This is a valuable addition, thanks! I tested it locally and it works as expected.

**Review by hblitza — APPROVED** [review]

**Comment by dnlkoch** [comment]
If this is a breaking change, the commit should be [adjusted accordingly](https://www.conventionalcommits.org/en/v1.0.0/) and some migration notes should be added.

**Pull request merged**
